FROM {{image}}
MAINTAINER Mekom Solutions <info@mekomsolutions.com>

RUN yum update -y 
RUN yum install -y openssh-server
RUN yum install -y sudo
RUN yum install -y nano

RUN yum install -y epel-release
RUN yum install -y python-pip
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools

RUN mkdir -p /etc/bahmni-installer
COPY ./link-mounted-folders.sh /etc/bahmni-installer/
COPY ./{{distribution}}-local.inventory /etc/bahmni-installer/local.inventory
COPY ./update-apache-config.sh /etc/bahmni-installer/

ENTRYPOINT service mysqld restart ; bahmni -i local.inventory start ; /bin/bash